version: '3.8'
services:
  web:
    build: 
      dockerfile: Dockerfile

    ports:
      - "9999:5000"
    
    environment:
      - FLASK_ENV=development

    volumes:
      - .:/app
      - ./model_cache:/root/.cache/